// Phantasy Star Portable
// #ID = 3738

// In Game Titles
/////////////////////////////////////////////////////////////////
//$1035070 
//*b0 - Adahna Slayer - Defeated 5 Adahna Degahnas
//*b1 - Magas Slayer - Defeated 5 Magas Maggahnas
//*b2 - Fakis 1st Slayer - Defeated Dulk Fakis Form 1, 5 times
//*b3 - Fakis 2nd Slayer - Defeated Dulk Fakis Form 2, 5 times
//*b4 - Super Rookie - Defeated 100 creatures
//*b5 - Super Ace - Defeated 500 creatures
//*b6 - Super Elite - Defeated 1000 creatures
//*b7 - Super Hero - Defeated 10000 creatures

// $1035071
//*b0 - Creature Master - Defeated all creatures
//*b1 - Combat Newcomer - Cleared free missions 3 times
//*b2 - Up and Coming - Cleared free missiosn 10 times
//*b3 - One to Watch - Cleared free missions 25 times
//*b4 - Top Contender - Cleared free missions 50 times
//*b5 - Ultimate Warrior - Cleared free missions 100 times
//*b7 - Young Guardian - Reached level 10

// $1035072
//*b0 - Zealous Guardian - Reached level 20
//*b1 - Solid Guardian - Reached level 30
//*b2 - Guardian Officer - Reached level 40
//*b3 - Superior Guardian - Reached level 50
//*b4 - 1st Class Guardian - Reached level 60
//*b5 - Guardian Instructor - Reached level 70
//*b6 - Elite Guardian - Reached level 80
//*b7 - Guardian Hero - Reached level 90

// $1035073
//*b0 - Ultimate Guardian - Reached level 100
//*b1 - Skill Master - Raised 10 skills to level 30
//*b2 - Bullet Master - Raised 10 bullets to level 30
//*b3 - TECHNIC Master - Raised 10 TECHNICs to level 30
//*b4 - Angry Soldier - Reached Hunter level 5
//*b5 - Whirlwind Slicer - Reached Hunter level 10
//*b6 - Quiet Hunter - Reached Ranger level 5
//*b7 - Lone Sniper - Reached Ranger level 10

// $1035074
//*b0 - Shining Mage - Reached Force level 5
//*b1 - Photon Wizard - Reached Force level 10
//*b2 - Flying Berzerker - Reached Fighmaster level 5
//*b3 - Mega Destroyer - Reached Fighmaster level 10
//*b4 - Magnificent Gunner - Reached Gunmaster level 5
//*b5 - Supreme Assassin - Reached Gunmaster level 10
//*b6 - Spirit Sorceror - Reached Masterforce level 5
//*b7 - Photon Protector - Reached Masterforce level 10

// $1035075
//*b0 - Hurricane Striker - Reached Acromaster level 5
//*b1 - Light Speed Killer - Reached Acromaster level 10
//*b2 - Stealthy Tactician - Reached Protranser level 5
//*b3 - Explosive Maestro - Reached Protranser level 10
//*b4 - Mobile Defense - Cleared Chapter 1 in story mode
//*b5 - Intel Section - Cleared Chapter 2 in story mode
//*b6 - SEED Intel Section - Cleared Chapter 3 in story mode
//*b7 - R&D Section - Cleared Chapter 4 in story mode

// $1035076
//*b0 - Rogue Family - Cleared Chapter 5 in story mode
//*b1 - Armed Servant - Cleared Chapter 6 in story mode
//*b2 - AMF Elite Unite - Cleared Chapter 7 in story mode
//*b3 - Eternal Traveler - Cleared Chapter 8 in story mode
//*b5 - Crusher - Maximum damage exceeded 300
//*b6 - Berserker - Maximum damage exceeded 600
//*b7 - Annihilator - Maximum damage exceeded 1800

// $1035077
//*b0 - Meseta Tycoon - Total Meseta reached 1,000,000
//*b1 - Sword Collector - Collected 80% of all swords
//*b2 - Knuckle Collector - Collected 80% of all knuckles
//*b3 - Spear Collector - Collected 80% of all spears
//*b4 - D. Saber Collector - Collected 80% of all double sabers
//*b5 - Axe Collector - Collected 80% of all axes
//*b6 - T. Saber Collector - Collected 80% of all twin sabers
//*b7 - T. Dagger Collector - Collected 80% of all twin daggers

// $1035078
//*b0 - T. Claw Collector - Collected 80% of all twin claws
//*b1 - Saber Collector - Collected 80% of all sabers
//*b2 - Dagger Collector - Collected 80% of all daggers
//*b3 - Claw Collector - Collected 80% of all claws
//*b4 - Whip Collector - Collected 80% of all whips
//*b5 - Slicer Collector - Collected 80% of all slicers
//*b6 - Rifle Collector - Collected 80% of all rifles
//*b7 - Shotgun Collector - Collected 80% of all shotguns

// $1035079
//*b0 - Longbow Collector - Collected 80% of all long bows
//*b1 - Grenade Collector - Collected 80% of all grenades
//*b2 - Laser Collector - Collected 80% of all lasers
//*b3 - T.H. Gun Collector - Collected 80% of all twin handguns
//*b4 - Handgun Collector - Collected 80% of all handguns
//*b5 - Crossbow Collector - Collected 80% of all crossbows
//*b6 - Card Collector - Collected 80% of all cards
//*b7 - M. Gun Collector -  Collected 80% of all machine guns

// $103507a
//*b0 - R Mag Collector - Collected 80% of all ranged mags
//*b1 - Rod Collector - Collected 80% of all rods
//*b2 - Wand Collector - Collected 80% of all wands
//*b3 - TECH Mag Collector - Collected 80% of all TECHNIC mags
//*b4 - Cooking Fighter - Obtain a grilling weapon
//*b5 - Colony Tourist - Completed all G. Colony free missions
//*b6 - Parum Tourist - Completed all Parum free missions
//*b7 - Neudaiz Tourist - Completed all Neudaiz free missions

// $103507b
//*b0 - Moatoob Tourist - Completed all Moatoob free missions
//*b2 - Title Collector - Collected 30 titles
//*b3 - PS Perfect - Collected all titles
/////////////////////////////////////////////////////////////////

cheevo = {
    "adahna_slayer":bit0(0x1035070),
    "magas_slayer":bit1(0x1035070),
    "fakis_first_slayer":bit2(0x1035070),
    "fakis_second_slayer":bit3(0x1035070),
    "super_rookie":bit4(0x1035070),
    "super_ace":bit5(0x1035070),
    "super_elite":bit6(0x1035070),
    "super_hero":bit7(0x1035070),
    "creature_master":bit0(0x1035071),
    "combat_newcomer":bit1(0x1035071),
    "up_and_coming":bit2(0x1035071),
    "one_to_watch":bit3(0x1035071),
    "top_contender":bit4(0x1035071),
    "ultimate_warrior":bit5(0x1035071),
    "rookie_guardian":bit6(0x1035071),
    "young_guardian":bit7(0x1035071),
    "zealous_guardian":bit0(0x1035072),
    "solid_guardian":bit1(0x1035072),
    "guardian_officer":bit2(0x1035072),
    "superior_guardian":bit3(0x1035072),
    "first_class_guardian":bit4(0x1035072),
    "guardian_instructor":bit5(0x1035072),
    "elite_guardian":bit6(0x1035072),
    "guardian_hero":bit7(0x1035072),
    "ultimate_guardian":bit0(0x1035073),
    "skill_master":bit1(0x1035073),
    "bullet_master":bit2(0x1035073),
    "technic_master":bit3(0x1035073),
    "angry_soldier":bit4(0x1035073),
    "whirlwind_slicer":bit5(0x1035073),
    "quiet_hunter":bit6(0x1035073),
    "lone_sniper":bit7(0x1035073),
    "shining_mage":bit0(0x1035074),
    "photon_wizard":bit1(0x1035074),
    "flying_berzerker":bit2(0x1035074),
    "mega_destroyer":bit3(0x1035074),
    "magnificent_gunner":bit4(0x1035074),
    "supreme_assassin":bit5(0x1035074),
    "spirit_sorceror":bit6(0x1035074),
    "photon_protector":bit7(0x1035074),
    "hurricane_striker":bit0(0x1035075),
    "light_speed_killer":bit1(0x1035075),
    "stealthy_tactician":bit2(0x1035075),
    "explosive_maestro":bit3(0x1035075),
    "mobile_defense":bit4(0x1035075),
    "intel_section":bit5(0x1035075),
    "seed_intel_section":bit6(0x1035075),
    "rd_section":bit7(0x1035075),
    "rogue_family":bit0(0x1035076),
    "armed_servant":bit1(0x1035076),
    "amf_elite_unite":bit2(0x1035076),
    "eternal_traveler":bit3(0x1035076),
    "willing_martyr":bit4(0x1035076),
    "crusher":bit5(0x1035076),
    "berserker":bit6(0x1035076),
    "annihilator":bit7(0x1035076),
    "meseta_tycoon":bit0(0x1035077),
    "sword_collector":bit1(0x1035077),
    "knuckle_collector":bit2(0x1035077),
    "spear_collector":bit3(0x1035077),
    "d_saber_collector":bit4(0x1035077),
    "axe_collector":bit5(0x1035077),
    "t_saber_collector":bit6(0x1035077),
    "t_dagger_collector":bit7(0x1035077),
    "t_claw_collector":bit0(0x1035078),
    "saber_collector":bit1(0x1035078),
    "dagger_collector":bit2(0x1035078),
    "claw_collector":bit3(0x1035078),
    "whip_collector":bit4(0x1035078),
    "slicer_collector":bit5(0x1035078),
    "rifle_collector":bit6(0x1035078),
    "shotgun_collector":bit7(0x1035078),
    "longbow_collector":bit0(0x1035079),
    "grenade_collector":bit1(0x1035079),
    "laser_collector":bit2(0x1035079),
    "th_gun_collector":bit3(0x1035079),
    "handgun_collector":bit4(0x1035079),
    "crossbow_collector":bit5(0x1035079),
    "card_collector":bit6(0x1035079),
    "m_gun_collector":bit7(0x1035079),
    "r_mag_collector":bit0(0x103507a),
    "rod_collector":bit1(0x103507a),
    "wand_collector":bit2(0x103507a),
    "tech_mag_collector":bit3(0x103507a),
    "cooking_fighter":bit4(0x103507a),
    "colony_tourist":bit5(0x103507a),
    "parum_tourist":bit6(0x103507a),
    "neudaiz_tourist":bit7(0x103507a),
    "moatoob_tourist":bit0(0x103507b),
    "title_collector":bit2(0x103507b),
    "ps_perfect":bit3(0x103507b),
}

function save_protect() => prev(dword(0x1035244)) != 0x00 
// Checks that you've killed at least 1 monster since the previous frame, preventing trigger upon save loading

achievement ("Adahna Slayer", "Defeated 5 Adahna Degahnas", 10, 
trigger = save_protect() && cheevo["adahna_slayer"] > prev(cheevo["adahna_slayer"]))

achievement ("Magas Slayer", "Defeated 5 Magas Maggahnas", 10, 
trigger = save_protect() && cheevo["magas_slayer"] > prev(cheevo["magas_slayer"]))

achievement ("Fakis 1st Slayer", "Defeated Dulk Fakis Form 1, 5 times", 10, 
trigger = save_protect() && cheevo["fakis_first_slayer"] > prev(cheevo["fakis_first_slayer"]))

achievement ("Fakis 2nd Slayer", "Defeated Dulk Fakis Form 2, 5 times", 10, 
trigger = save_protect() && cheevo["fakis_second_slayer"] > prev(cheevo["fakis_second_slayer"]))

achievement ("Super Rookie", "Defeated 100 creatures", 5, 
trigger = save_protect() && cheevo["super_rookie"] > prev(cheevo["super_rookie"]))

achievement ("Super Ace", "Defeated 500 creatures", 5, 
trigger = save_protect() && cheevo["super_ace"] > prev(cheevo["super_ace"]))

achievement ("Super Elite", "Defeated 1000 creatures", 5, 
trigger = save_protect() && cheevo["super_elite"] > prev(cheevo["super_elite"]))

achievement ("Super Hero", "Defeated 10000 creatures", 10, 
trigger = save_protect() && cheevo["super_hero"] > prev(cheevo["super_hero"]))

achievement ("Creature Master", "Defeated all creatures", 25, 
trigger = save_protect() && cheevo["creature_master"] > prev(cheevo["creature_master"]))

achievement ("Combat Newcomer", "Cleared free missions 3 times", 5, 
trigger = save_protect() && cheevo["combat_newcomer"] > prev(cheevo["combat_newcomer"]))

achievement ("Up and Coming", "Cleared free missiosn 10 times", 5, 
trigger = save_protect() && cheevo["up_and_coming"] > prev(cheevo["up_and_coming"]))

achievement ("One to Watch", "Cleared free missions 25 times", 5, 
trigger = save_protect() && cheevo["one_to_watch"] > prev(cheevo["one_to_watch"]))

achievement ("Top Contender", "Cleared free missions 50 times", 5, 
trigger = save_protect() && cheevo["top_contender"] > prev(cheevo["top_contender"]))

achievement ("Ultimate Warrior", "Cleared free missions 100 times", 10, 
trigger = save_protect() && cheevo["ultimate_warrior"] > prev(cheevo["ultimate_warrior"]))

achievement ("Young Guardian", "Reached level 10", 5, 
trigger = save_protect() && cheevo["young_guardian"] > prev(cheevo["young_guardian"]))

achievement ("Zealous Guardian", "Reached level 20", 5, 
trigger = save_protect() && cheevo["zealous_guardian"] > prev(cheevo["zealous_guardian"]))

achievement ("Solid Guardian", "Reached level 30", 5, 
trigger = save_protect() && cheevo["solid_guardian"] > prev(cheevo["solid_guardian"]))

achievement ("Guardian Officer", "Reached level 40", 5, 
trigger = save_protect() && cheevo["guardian_officer"] > prev(cheevo["guardian_officer"]))

achievement ("Superior Guardian", "Reached level 50", 5, 
trigger = save_protect() && cheevo["superior_guardian"] > prev(cheevo["superior_guardian"]))

achievement ("1st Class Guardian", "Reached level 60", 5, 
trigger = save_protect() && cheevo["first_class_guardian"] > prev(cheevo["first_class_guardian"]))

achievement ("Guardian Instructor", "Reached level 70", 10, 
trigger = save_protect() && cheevo["guardian_instructor"] > prev(cheevo["guardian_instructor"]))

achievement ("Elite Guardian", "Reached level 80", 10, 
trigger = save_protect() && cheevo["elite_guardian"] > prev(cheevo["elite_guardian"]))

achievement ("Guardian Hero", "Reached level 90", 10, 
trigger = save_protect() && cheevo["guardian_hero"] > prev(cheevo["guardian_hero"]))

achievement ("Ultimate Guardian", "Reached level 100", 25, 
trigger = save_protect() && cheevo["ultimate_guardian"] > prev(cheevo["ultimate_guardian"]))

achievement ("Skill Master", "Raised 10 skills to level 30", 5, 
trigger = save_protect() && cheevo["skill_master"] > prev(cheevo["skill_master"]))

achievement ("Bullet Master", "Raised 10 bullets to level 30", 5, 
trigger = save_protect() && cheevo["bullet_master"] > prev(cheevo["bullet_master"]))

achievement ("TECHNIC Master", "Raised 10 TECHNICs to level 30", 5, 
trigger = save_protect() && cheevo["technic_master"] > prev(cheevo["technic_master"]))

achievement ("Angry Soldier", "Reached Hunter level 5", 5, 
trigger = save_protect() && cheevo["angry_soldier"] > prev(cheevo["angry_soldier"]))

achievement ("Whirlwind Slicer", "Reached Hunter level 10", 5, 
trigger = save_protect() && cheevo["whirlwind_slicer"] > prev(cheevo["whirlwind_slicer"]))

achievement ("Quiet Hunter", "Reached Ranger level 5", 5, 
trigger = save_protect() && cheevo["quiet_hunter"] > prev(cheevo["quiet_hunter"]))

achievement ("Lone Sniper", "Reached Ranger level 10", 5, 
trigger = save_protect() && cheevo["lone_sniper"] > prev(cheevo["lone_sniper"]))

achievement ("Shining Mage", "Reached Force level 5", 5, 
trigger = save_protect() && cheevo["shining_mage"] > prev(cheevo["shining_mage"]))

achievement ("Photon Wizard", "Reached Force level 10", 5, 
trigger = save_protect() && cheevo["photon_wizard"] > prev(cheevo["photon_wizard"]))

achievement ("Flying Berzerker", "Reached Fighmaster level 5", 5, 
trigger = save_protect() && cheevo["flying_berzerker"] > prev(cheevo["flying_berzerker"]))

achievement ("Mega Destroyer", "Reached Fighmaster level 10", 5, 
trigger = save_protect() && cheevo["mega_destroyer"] > prev(cheevo["mega_destroyer"]))

achievement ("Magnificent Gunner", "Reached Gunmaster level 5", 5, 
trigger = save_protect() && cheevo["magnificent_gunner"] > prev(cheevo["magnificent_gunner"]))

achievement ("Supreme Assassin", "Reached Gunmaster level 10", 5, 
trigger = save_protect() && cheevo["supreme_assassin"] > prev(cheevo["supreme_assassin"]))

achievement ("Spirit Sorceror", "Reached Masterforce level 5", 5, 
trigger = save_protect() && cheevo["spirit_sorceror"] > prev(cheevo["spirit_sorceror"]))

achievement ("Photon Protector", "Reached Masterforce level 10", 5, 
trigger = save_protect() && cheevo["photon_protector"] > prev(cheevo["photon_protector"]))

achievement ("Hurricane Striker", "Reached Acromaster level 5", 5, 
trigger = save_protect() && cheevo["hurricane_striker"] > prev(cheevo["hurricane_striker"]))

achievement ("Light Speed Killer", "Reached Acromaster level 10", 5, 
trigger = save_protect() && cheevo["light_speed_killer"] > prev(cheevo["light_speed_killer"]))

achievement ("Stealthy Tactician", "Reached Protranser level 5", 5, 
trigger = save_protect() && cheevo["stealthy_tactician"] > prev(cheevo["stealthy_tactician"]))

achievement ("Explosive Maestro", "Reached Protranser level 10", 5, 
trigger = save_protect() && cheevo["explosive_maestro"] > prev(cheevo["explosive_maestro"]))

achievement ("Mobile Defense", "Cleared Chapter 1 in story mode", 10, 
trigger = save_protect() && cheevo["mobile_defense"] > prev(cheevo["mobile_defense"]))

achievement ("Intel Section", "Cleared Chapter 2 in story mode", 10, 
trigger = save_protect() && cheevo["intel_section"] > prev(cheevo["intel_section"]))

achievement ("SEED Intel Section", "Cleared Chapter 3 in story mode", 10, 
trigger = save_protect() && cheevo["seed_intel_section"] > prev(cheevo["seed_intel_section"]))

achievement ("R&D Section", "Cleared Chapter 4 in story mode", 10, 
trigger = save_protect() && cheevo["rd_section"] > prev(cheevo["rd_section"]))

achievement ("Rogue Family", "Cleared Chapter 5 in story mode", 10, 
trigger = save_protect() && cheevo["rogue_family"] > prev(cheevo["rogue_family"]))

achievement ("Armed Servant", "Cleared Chapter 6 in story mode", 10, 
trigger = save_protect() && cheevo["armed_servant"] > prev(cheevo["armed_servant"]))

achievement ("AMF Elite Unite", "Cleared Chapter 7 in story mode", 10, 
trigger = save_protect() && cheevo["amf_elite_unite"] > prev(cheevo["amf_elite_unite"]))

achievement ("Eternal Traveler", "Cleared Chapter 8 in story mode", 10, 
trigger = save_protect() && cheevo["eternal_traveler"] > prev(cheevo["eternal_traveler"]))

achievement ("Crusher", "Maximum damage exceeded 300", 5, 
trigger = save_protect() && cheevo["crusher"] > prev(cheevo["crusher"]))

achievement ("Berserker", "Maximum damage exceeded 600", 5, 
trigger = save_protect() && cheevo["berserker"] > prev(cheevo["berserker"]))

achievement ("Annihilator", "Maximum damage exceeded 1800", 10, 
trigger = save_protect() && cheevo["annihilator"] > prev(cheevo["annihilator"]))

achievement ("Meseta Tycoon", "Total Meseta reached 1,000,000", 5, 
trigger = save_protect() && cheevo["meseta_tycoon"] > prev(cheevo["meseta_tycoon"]))

function s_rank() => dword(0x1035884)
achievement ("Super S", "Obtain 25 S-ranks's", 25,
trigger = save_protect() && measured(s_rank() == 25) && prev(s_rank()) == 24)

achievement ("Sword Collector", "Collected 80% of all swords", 25, 
trigger = save_protect() && cheevo["sword_collector"] > prev(cheevo["sword_collector"]))

achievement ("Knuckle Collector", "Collected 80% of all knuckles", 25, 
trigger = save_protect() && cheevo["knuckle_collector"] > prev(cheevo["knuckle_collector"]))

achievement ("Spear Collector", "Collected 80% of all spears", 25, 
trigger = save_protect() && cheevo["spear_collector"] > prev(cheevo["spear_collector"]))

achievement ("D. Saber Collector", "Collected 80% of all double sabers", 25, 
trigger = save_protect() && cheevo["d_saber_collector"] > prev(cheevo["d_saber_collector"]))

achievement ("Axe Collector", "Collected 80% of all axes", 25, 
trigger = save_protect() && cheevo["axe_collector"] > prev(cheevo["axe_collector"]))

achievement ("T. Saber Collector", "Collected 80% of all twin sabers", 25, 
trigger = save_protect() && cheevo["t_saber_collector"] > prev(cheevo["t_saber_collector"]))

achievement ("T. Dagger Collector", "Collected 80% of all twin daggers", 25, 
trigger = save_protect() && cheevo["t_dagger_collector"] > prev(cheevo["t_dagger_collector"]))

achievement ("T. Claw Collector", "Collected 80% of all twin claws", 25, 
trigger = save_protect() && cheevo["t_claw_collector"] > prev(cheevo["t_claw_collector"]))

achievement ("Saber Collector", "Collected 80% of all sabers", 25, 
trigger = save_protect() && cheevo["saber_collector"] > prev(cheevo["saber_collector"]))

achievement ("Dagger Collector", "Collected 80% of all daggers", 25, 
trigger = save_protect() && cheevo["dagger_collector"] > prev(cheevo["dagger_collector"]))

achievement ("Claw Collector", "Collected 80% of all claws", 25, 
trigger = save_protect() && cheevo["claw_collector"] > prev(cheevo["claw_collector"]))

achievement ("Whip Collector", "Collected 80% of all whips", 25, 
trigger = save_protect() && cheevo["whip_collector"] > prev(cheevo["whip_collector"]))

achievement ("Slicer Collector", "Collected 80% of all slicers", 25, 
trigger = save_protect() && cheevo["slicer_collector"] > prev(cheevo["slicer_collector"]))

achievement ("Rifle Collector", "Collected 80% of all rifles", 25, 
trigger = save_protect() && cheevo["rifle_collector"] > prev(cheevo["rifle_collector"]))

achievement ("Shotgun Collector", "Collected 80% of all shotguns", 25, 
trigger = save_protect() && cheevo["shotgun_collector"] > prev(cheevo["shotgun_collector"]))

achievement ("Longbow Collector", "Collected 80% of all long bows", 25, 
trigger = save_protect() && cheevo["longbow_collector"] > prev(cheevo["longbow_collector"]))

achievement ("Grenade Collector", "Collected 80% of all grenades", 25, 
trigger = save_protect() && cheevo["grenade_collector"] > prev(cheevo["grenade_collector"]))

achievement ("Laser Collector", "Collected 80% of all lasers", 25, 
trigger = save_protect() && cheevo["laser_collector"] > prev(cheevo["laser_collector"]))

achievement ("T.H. Gun Collector", "Collected 80% of all twin handguns", 25, 
trigger = save_protect() && cheevo["th_gun_collector"] > prev(cheevo["th_gun_collector"]))

achievement ("Handgun Collector", "Collected 80% of all handguns", 25, 
trigger = save_protect() && cheevo["handgun_collector"] > prev(cheevo["handgun_collector"]))

achievement ("Crossbow Collector", "Collected 80% of all crossbows", 25, 
trigger = save_protect() && cheevo["crossbow_collector"] > prev(cheevo["crossbow_collector"]))

achievement ("Card Collector", "Collected 80% of all cards", 25, 
trigger = save_protect() && cheevo["card_collector"] > prev(cheevo["card_collector"]))

achievement ("M. Gun Collector", "Collected 80% of all machine guns", 25, 
trigger = save_protect() && cheevo["m_gun_collector"] > prev(cheevo["m_gun_collector"]))

achievement ("R Mag Collector", "Collected 80% of all ranged mags", 25, 
trigger = save_protect() && cheevo["r_mag_collector"] > prev(cheevo["r_mag_collector"]))

achievement ("Rod Collector", "Collected 80% of all rods", 25, 
trigger = save_protect() && cheevo["rod_collector"] > prev(cheevo["rod_collector"]))

achievement ("Wand Collector", "Collected 80% of all wands", 10, 
trigger = save_protect() && cheevo["wand_collector"] > prev(cheevo["wand_collector"]))

achievement ("TECH Mag Collector", "Collected 80% of all TECHNIC mags", 25, 
trigger = save_protect() && cheevo["tech_mag_collector"] > prev(cheevo["tech_mag_collector"]))

achievement ("Cooking Fighter", "Obtain a grilling weapon", 10, 
trigger = save_protect() && cheevo["cooking_fighter"] > prev(cheevo["cooking_fighter"]))

achievement ("Colony Tourist", "Completed all G. Colony free missions", 10, 
trigger = save_protect() && cheevo["colony_tourist"] > prev(cheevo["colony_tourist"]))

achievement ("Parum Tourist", "Completed all Parum free missions", 10, 
trigger = save_protect() && cheevo["parum_tourist"] > prev(cheevo["parum_tourist"]))

achievement ("Neudaiz Tourist", "Completed all Neudaiz free missions", 10, 
trigger = save_protect() && cheevo["neudaiz_tourist"] > prev(cheevo["neudaiz_tourist"]))

achievement ("Moatoob Tourist", "Completed all Moatoob free missions", 10, 
trigger = save_protect() && cheevo["moatoob_tourist"] > prev(cheevo["moatoob_tourist"]))

achievement ("Title Collector", "Collected 30 titles", 10, 
trigger = save_protect() && cheevo["title_collector"] > prev(cheevo["title_collector"]))

achievement ("PS Perfect", "Collected all titles", 25, 
trigger = save_protect() && cheevo["ps_perfect"] > prev(cheevo["ps_perfect"]))